BeautyCity/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('beauty.urls', namespace='beauty')),
    path('', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

beauty/urls.py
from django.urls import path
from beauty.views import get_available_time, index, service, service_finally, notes, create_appointment
from beauty.views import get_masters, index, get_categories, service, service_finally, notes

app_name = 'beauty'

urlpatterns = [
    path('', index, name='index'),
    path('service', service, name='service'),
    path('service_finally', service_finally, name='service_finally'),
    path('notes', notes, name='notes'),
    path('api/categories', get_categories),
    path('api/masters', get_masters),
    path('api/get_available_time', get_available_time),
    path('notes', notes, name='notes'),
    path('create_appointment', create_appointment, name='create_appointment')
]

users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('users/request_code', views.request_code),
    path('users/confirm_registration', views.confirm_registration),
    path('users/logout', views.logout_user),
]

beauty/models.py
from phonenumber_field.modelfields import PhoneNumberField
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from users.models import User


class Category(models.Model):
    name = models.CharField(
        'Категория',
        max_length=25
    )

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Procedure(models.Model):
    name = models.CharField(
        'название',
        max_length=50,
    )
    price = models.IntegerField(
        verbose_name='Цена',
        validators=[MinValueValidator(0)]
    )
    image = models.FileField(
        'картинка',
        null=True,
        upload_to='media/',
        blank=True
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name='services',
        default=None,
        verbose_name='Категории'
    )

    def __str__(self):
        return f'{self.name}. {self.price}'

    class Meta:
        verbose_name = 'Процедура'
        verbose_name_plural = 'Процедуры'


class Employee(models.Model):

    name = models.CharField(
        'Имя',
        max_length=50
    )
    surname = models.CharField(
        'Фамилия',
        max_length=80
    )
    avatar = models.FileField(
        'аватар',
        null=True,
        upload_to='media/',
        blank=True
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        default=None,
        verbose_name='Специальность'
    )

    def __str__(self):
        return f'{self.name} {self.surname}'

    class Meta:
        verbose_name = 'Работник'
        verbose_name_plural = 'Работники'


class Salon (models.Model):

    name = models.CharField(
        'Название',
        max_length=50
    )
    address = models.CharField(
        'Адрес',
        max_length=100,
        blank=True
    )
    image = models.FileField(
        'Картинка',
        null=True,
        upload_to='media/',
        blank=True
    )
    employee = models.ManyToManyField(
        'Employee',
        through='DayOfWork',
        through_fields=('salons', 'employees')
    )

    def __str__(self):
        return f'{self.name} {self.address}'

    class Meta:
        verbose_name = 'Салон'
        verbose_name_plural = 'Салоны'


class Feedback(models.Model):
    feedback_text = models.TextField(
        'Текст'
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='user_reviews'
    )
    value = models.IntegerField(
        'Оценка',
        validators=[MinValueValidator(0), MaxValueValidator(5)]
    )
    employee = models.ForeignKey(
        Employee,
        on_delete=models.CASCADE,
        related_name='feedbacks',
        verbose_name='Мастер',
        default=None
    )

    def __str__(self):
        return f' Оценка - {self.value}'

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'


class DayOfWork(models.Model):
    MONDAY = 'Mo'
    TUESDAY = 'Tu'
    WEDNESDAY = 'We'
    THURSDAY = 'Td'
    FRIDAY = 'Fr'
    SATURDAY = 'Sa'
    SUNDAY = 'Su'

    DAYS_OF_WEEK = [
        (MONDAY, 'Пн'),
        (TUESDAY, 'Вт'),
        (WEDNESDAY, 'Ср'),
        (THURSDAY, 'Чт'),
        (FRIDAY, 'Пт'),
        (SATURDAY, 'Сб'),
        (SUNDAY, 'Вс')
    ]

    day_of_week = models.CharField(
        max_length=20,
        verbose_name='Рабочие дни',
        choices=DAYS_OF_WEEK,
        blank=True
    )

    ready = models.BooleanField(
        default=False
    )

    employees = models.ForeignKey(
        Employee,
        on_delete=models.CASCADE,
        related_name='day_of_works',
        verbose_name='Мастер'
    )

    salons = models.ForeignKey(
        Salon,
        on_delete=models.CASCADE,
        related_name='day_of_works'
    )


class Appointment(models.Model):

    MORNING_1 = '9:00'
    MORNING_2 = '10:00'
    MORNING_3 = '11:00'
    AFTERNOON_1 = '12:00'
    AFTERNOON_2 = '13:00'
    AFTERNOON_3 = '14:00'
    DAY_1 = '15:00'
    DAY_2 = '16:00'
    DAY_3 = '17:00'
    EVENING_1 = '18:00'
    EVENING_2 = '19:00'
    EVENING_3 = '20:00'
    day_times = {
        MORNING_1, MORNING_2, MORNING_2, MORNING_3, AFTERNOON_1, AFTERNOON_2,
        AFTERNOON_3, DAY_1, DAY_2, DAY_3, EVENING_1, EVENING_2, EVENING_3
    }
    WORK_HOURS = [
        (MORNING_1, MORNING_1),
        (MORNING_2, MORNING_2),
        (MORNING_3, MORNING_3),
        (AFTERNOON_1, AFTERNOON_1),
        (AFTERNOON_2, AFTERNOON_2),
        (AFTERNOON_3, AFTERNOON_3),
        (DAY_1, DAY_1),
        (DAY_2, DAY_2),
        (DAY_3, DAY_3),
        (EVENING_1, EVENING_1),
        (EVENING_2, EVENING_2),
        (EVENING_3, EVENING_3),
    ]
    procedure = models.ForeignKey(
        Procedure,
        on_delete=models.CASCADE,
        related_name='appointment',
        verbose_name='Процедура',
        default=None
    )
    employee = models.ForeignKey(
        Employee,
        on_delete=models.CASCADE,
        related_name='appointments',
        verbose_name='Мастер'
    )
    salon = models.ForeignKey(
        Salon,
        on_delete=models.CASCADE,
        related_name='appointments'
    )
    appointment_hour = models.CharField(
        max_length=15,
        verbose_name='Время записи',
        choices=WORK_HOURS,
        blank=True
    )
    user = models.ForeignKey(
        User,
        related_name='appointments',
        null=True,
        blank=True,
        on_delete=models.CASCADE
    )
    question = models.TextField(
        'вопрос',
        null=True,
        blank=True
    )
    client_name = models.CharField('имя клиента', max_length=100, null=True, blank=True)
    date = models.DateField(
        'Дата',
        null=True
    )

    def __str__(self):
        return f'{self.employee}'

    class Meta:
        verbose_name = 'Приём'
        verbose_name_plural = 'Приёмы'

beauty/forms.py
from django import forms

from phonenumber_field.formfields import PhoneNumberField
from django.forms import CharField

from users.models import User
from .models import Appointment


class AppointmentForm(forms.ModelForm):
    phone_number = PhoneNumberField()
    question = CharField()
    client_name = CharField()

    class Meta:
        model = Appointment
        fields = (
            'procedure', 'employee', 'salon', 'appointment_hour', 'date', 'phone_number', 'question', 'client_name'
        )

    def save(self, commit=True):
        appointment = super(AppointmentForm, self).save(commit=False)
        user = User.objects.get(phonenumber=self.cleaned_data['phone_number'])
        appointment.user_id = user.id
        if commit:
            appointment.save()
        return appointment

beauty/views.py
import datetime

from django.shortcuts import render, redirect
from django.contrib import messages

from rest_framework.decorators import api_view
from rest_framework.response import Response

from .models import Appointment, DayOfWork
from .models import Salon, Procedure, Employee, Feedback, Category
from users.models import User
from users.forms import UserToCallForm
from .serializers import EmployeeAppointmentDetailSerializer, RequestAvailableTimeSerializer, \
    RequestMastersForAppointmentDetailSerializer, ServiceCategoryAppointmentDetailSerializer
from .forms import AppointmentForm


def index(request):
    salons = Salon.objects.all()
    procedures = Procedure.objects.all()
    employees = Employee.objects.all()
    feedbacks = Feedback.objects.all()
    context = {
        'salons': salons,
        'procedures': procedures,
        'employees': employees,
        'feedbacks': feedbacks,
        'is_authenticated': request.user.is_authenticated
    }

    if request.method == 'POST':
        form = UserToCallForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(request.path)
    else:
        form = UserToCallForm()
    context['form'] = form

    return render(request, 'beauty/index.html', context)


def service(request):
    salons = Salon.objects.all()
    categories = Category.objects.all()
    service_items = []

    context = {
        'salons': salons,
        'is_authenticated': request.user.is_authenticated
    }

    for category in categories:
        service_item = {
            category.name: {
                procedure.name: procedure.price for procedure in category.services.all()}
        }
        service_items.append(service_item)

    context['service_items'] = service_items
    return render(request, 'beauty/service.html', context=context)


@api_view(['GET'])
def get_categories(request):
    categories = Category.objects.all()
    serializer = ServiceCategoryAppointmentDetailSerializer(categories, many=True)
    return Response(serializer.data)


@api_view(['GET'])
def get_masters(request):
    request_serializer = RequestMastersForAppointmentDetailSerializer(request.query_params)

    master_ids = DayOfWork.objects.filter(
        salons__id=request_serializer.data['salon_id'],
        employees__category_id=request_serializer.data['category_id'],
    ).distinct().values_list('employees', flat=True)

    masters = Employee.objects.filter(id__in=master_ids)
    serializer = EmployeeAppointmentDetailSerializer(masters, many=True)

    return Response(data=serializer.data)


@api_view(['GET'])
def get_available_time(request):
    request_serializer = RequestAvailableTimeSerializer(request.query_params)

    try:
        employee_word_day = DayOfWork.objects.get(
            salons_id=request_serializer.data['salon_id'],
            employees_id=request_serializer.data['master_id'],
            day_of_week=request_serializer.data['weekday']
        )
    except DayOfWork.DoesNotExist:
        return Response([])

    if not employee_word_day.ready:
        return Response([])

    appointments = Appointment.objects.filter(
        employee_id=request_serializer.data['master_id'],
        salon_id=request_serializer.data['salon_id'],
        date=request_serializer.data['date']
    ).values_list('appointment_hour', flat=True)

    time_begins = set(map(lambda time: time.split(' - ')[0], appointments))
    free_times = list(Appointment.day_times.difference(time_begins))
    free_sorted_times = sorted(free_times, key=lambda time: datetime.datetime.strptime(time, '%H:%M'))
    return Response(free_sorted_times)


def service_finally(request):
    pass


def notes(request):
    user = request.user
    if user.is_authenticated:
        user = User.objects.get(phonenumber = str(user.phonenumber))
        appointments = Appointment.objects.filter(user=user)
        user_attrs = {
            'first_name': user.first_name,
            'last_name': user.last_name,
            'avatar': user.avatar,
            'appointments': appointments,
            'sum': sum([appointment.procedure.price for appointment in appointments])
        }
    return render(request, 'beauty/notes.html', context=user_attrs)


def create_appointment(request):
    if request.method == 'POST':
        form = AppointmentForm(request.POST)

        if not form.is_valid():
            messages.error(request, 'Вы ввели некорректные данные. Пожалуйста, попробуйте еще раз.')
            return redirect('beauty:service')

        form.save()
        messages.success(request, 'Вы успешно записались на прием.')
        return redirect('beauty:index')

    return redirect('beauty:index')

templates/beauty/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="{% static 'beauty/img/favicon.png' %}">
    {% csrf_token %}
	{% block title %}
    {% endblock %}
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css" integrity="sha512-yHknP1/AwR+yx26cB1y0cjvQUMvEa2PFzt1c9LlS4pRQ5NOTZFWbhBig+X9G9eYW/8m0/4OXNx8pxJ6z57x0dw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css" integrity="sha512-17EgCFERpgZKcm0j0fEq1YCJuyAWdz9KUtv1EjVuaOz8pDnh/0nZxmU6BBXwaaxqoi9PQXnRWqlcDB027hgv9A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    {%block css%}
    {% endblock %}
</head>
<section id="mobMenu">
			<div class="mobMenu">
				<div class="container">
				<div class="mobMenu__header">
					<div class="row">
						<div class="col-4 col-md-3">
							<a href="/">
								<img src="{% static 'beauty/img/Logo.svg' %}" alt="Logo" class="logo header__logo">
							</a>
						</div>
						<div class="col-3 col-md-2">
							<img src="{% static 'beauty/img/x.svg' %}" alt="x" class="mobMenuClose">
						</div>
					</div>
				</div>
				<div class="mobMenu__content">
					<div class="row">
						<div class="col-md-3">
							<nav>
								<ul class="mobMenu__menu">
									<li class="mobMenu__menu_item">
										<a href="#" class="mobMenu__menu_link">Мастера</a>
									</li>
									<li class="mobMenu__menu_item"><a href="#" class="mobMenu__menu_link">Услуги</a></li>
									<li class="mobMenu__menu_item"><a href="#" class="mobMenu__menu_link">Отзывы</a></li>
									<li class="mobMenu__menu_item"><a href="#" class="mobMenu__menu_link">Контакты</a></li>
                                    <li class="mobMenu__menu_item"><a href="#" class="mobMenu__menu_link">Контакты</a></li>
								</ul>
							</nav>
							<a href="#" class="mobMenu__account">Личный кабинет</a>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<button class="mobMenu__btn">Перезвоните мне</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<header id="header">
		<div class="container">
			<div class="header">
				<div class="row">
					<div class="col-2 col-md-2 mob">
						<img src="{% static 'beauty/img/hamburger.svg' %}" alt="hamburger" class="header__mobMenu">
					</div>
					<div class="col-5 col-md-3 col-lg-2">
						<a href="/">
							<img src="{% static 'beauty/img/Logo.svg' %}" alt="Logo" class="logo header__logo">
						</a>
					</div>
					<div class="col-md-5 ">
						<nav>
						<ul class="menu">
							<li class="menu__item"><a href="#masters" class="menu__item_link">Мастера</a></li>
							<li class="menu__item"><a href="#services" class="menu__item_link">Услуги</a></li>
							<li class="menu__item"><a href="#reviews" class="menu__item_link">Отзывы</a></li>
							<li class="menu__item"><a href="#footer" class="menu__item_link">Контакты</a></li>
                            {% if is_authenticated %}
                            <li class="menu__item"><a href="{% url 'beauty:notes'%}" class="mobMenu__account">Личный кабинет</a></li>
                            {% endif %}
						</ul>
					</nav>
					</div>
					<div class="col-2 col-md-2 col-lg-3">
						<div class="header__block">
                            {% if user.is_authenticated %}
                                <div class="header__block_user">
                                    <a href="tel:{{ user.phonenumber }}"><button class="header__block_btn">Перезвоните мне</button></a>
                                    <a class="header__block_user__intro" href="/users/logout">Выйти</a>
                                </div>
                            {% else %}
                                <div class="header__block_auth">
                                    <img src="{% static 'beauty/img/acc.svg' %}" alt="account" class="header__account_img">
                                    <span class="header__block_auth__intro">Войти</span>
						        </div>
                            {% endif %}
                        </div>
					</div>
				</div>
				
				
				
			</div>
		</div>
	</header>

{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success'  %}
            {% include 'beauty/alerts/success.html' with message=message%}
        {% elif message.tags == 'danger' %}
            {% include 'beauty/alerts/error.html' with message=message %}
        {% endif %}
    {% endfor %}
{%  endif%}
            
{% block content%} 
{% endblock %}

    <footer id="footer">
        <div class="container">
            <div class="footer">
                <div class="footer__block">
                    <div class="row">
                        <div class="col-md-3 col-lg-2">
                            <a href="/"><img src="{% static 'beauty/img/Logo.svg' %}" alt="logo" class="footer__logo"></a>
                        </div>
                        <div class="col-md-5 minMobHide">
                            <nav>
                                <ul class="menu">
                                    <li class="menu__item"><a href="#" class="menu__item_link">Мастера</a></li>
                                    <li class="menu__item"><a href="#" class="menu__item_link">Услуги</a></li>
                                    <li class="menu__item"><a href="#" class="menu__item_link">Отзывы</a></li>
                                    <li class="menu__item"><a href="#" class="menu__item_link">Контакты</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <div class="footer__contact">
                        <div class="row">
                            <div class="col-md-4">
                                
                                    <div class="footer__data">с 10:00 до 20:00  без выходных</div>
                                    
                            </div>
                            <div class="col-md-3">
                                <a href="tel:+79179023800" class="contacts__info_tel">+7 (917) 902 38 00</a>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-5 minMobShow">
                                <nav>
                                    <ul class="menu">
                                        <li class="menu__item"><a href="#" class="menu__item_link">Мастера</a></li>
                                        <li class="menu__item"><a href="#" class="menu__item_link">Услуги</a></li>
                                        <li class="menu__item"><a href="#" class="menu__item_link">Отзывы</a></li>
                                        <li class="menu__item"><a href="#" class="menu__item_link">Контакты</a></li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                    <div class="hr"></div>
                    <div class="footer__bottom">
                        <div class="row">
                            <div class="col-md-4 col-lg-3">
                                <a href="#" class="footer__link">Политика конфиденциальности</a>
                            </div>
                            <div class="col-md-3">
                                <div class="footer__copy">2022. Все права защищены</div>
                            </div>
                            <div class="col-md-3 col-lg-2">
                                <div class="footer__social fic">
                                    <a href=""><img src="{% static 'beauty/img/waGray.svg' %}" alt="wa" class="contacts__social_icon"></a>
                                    <a href=""><img src="{% static 'beauty/img/vkGray.svg' %}" alt="vk" class="contacts__social_icon"></a>
                                    <a href=""><img src="{% static 'beauty/img/tgGray.svg' %}" alt="tg" class="contacts__social_icon"></a>
                                    <a href=""><img src="{% static 'beauty/img/instaGray.svg' %}" alt="insta" class="contacts__social_icon"></a>
                                </div>
                            </div>
                        </div>
                        
                        
                        
                    </div>
                    
                </div>
            </div>
        </div>
    </footer>
</html>

templates/beauty/service.html
{% extends 'beauty/base.html' %}
{% load static %}
{%block title%}
	<title>Записаться</title>
{% endblock %}
{% block css%}
	<link rel="stylesheet" href="{% static 'beauty/css/bootstrap-grid.min.css' %}">
	<link rel="stylesheet" href="{% static 'beauty/css/air-datepicker.css' %}">
	<script src="{% static 'beauty/js/air-datepicker.js' %}"></script>
	<link rel="stylesheet" href="{% static 'beauty/css/main.css' %}">
{% endblock %}
{%block content%}
<body class="servicePage">
	<section id="service">
		<div class="container">
			<div class="service">
				<div class="breadCrumbs">
					<a href="#" class="breadCrumbs__item">На главную</a>
				</div>
				<div class="service__block">
					<h1 class="service__title">Запись на услугу</h1>
					<button class="service__btn btn">Запись по телефону</button>
				</div>
				
                <div class="dropdowns_container">
					<div class="service__form_block service__salons">
						<button class="accordion">(Выберите салон)</button>
						<div class="panel">
						    {%for salon in salons%}
						      <div
                                class="accordion__block accordion__salon_block fic"
                                data-salon_id="{{ salon.id }}"
                              >
						      	<div class="accordion__block_intro">{{salon.name}}</div>
						      	<div class="accordion__block_address">{{salon.address}}</div>
						      </div>
						    {% endfor %}
                        </div>
					</div>
			    </div>
            </div>
		</div>
	</section>
	<section id="time">
		<div class="container">
			<div class="time">
				<h2 class="time__title">Выберите время</h2>
				<div class="time__block">
					<div class="row">
						<div id="datepicker__container" class="col-md-4">
							<div id="datepickerHere"></div>
						</div>
						<div id="timepicker__container" class="col-md-8">
						</div>
					</div>
				</div>
				<div class="time__btns">
					<div class="row">
						<div class="col-md-12">
                            <a href='{% url 'beauty:index' %}'><button  class="time__btns_home">На главную</button></a>
                            <a id="submit_appointment_btn" href={% url 'beauty:service_finally' %}><button  class="time__btns_next">Далее</button></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
    <section id="confirm">
    <div class="confirm_appointment">
        <div class="container">
        <div class="serviceFinally">
            <div class="row">
                <div class="col-md-6 col-lg-6">
                    <div class="breadCrumbs">
                        <a href="#" class="breadCrumbs__item">На главную</a>
                    </div>
                    <div class="service__block">
                        <h1 class="service__title">Запись на услугу</h1>
                    </div>
                    <form id="serviceFinally__form" action="/create_appointment" class="serviceFinally__form" method="POST">
                        {% csrf_token %}
                        <input type="number" hidden name="procedure">
                        <input type="number" hidden name="employee">
                        <input type="number" hidden name="salon">
                        <input type="text" hidden name="appointment_hour">
                        <input type="text" hidden name="date">


                        <div class="serviceFinally__form_block">
                            <div class="serviceFinally__form_header fic">
                                <span class="serviceFinally__form_header__number">Запись</span>
                                <div class="serviceFinally__form_header__item fic">
                                    <div class="serviceFinally__form_header__service">BeautyCity Пушкинская</div>
                                    <div class="serviceFinally__form_header__address">ул. Пушкинская, д. 78А</div>
                                </div>
                            </div>
                            <div class="serviceFinally__form_content">
                                <div class="serviceFinally__form_content__block fic">
                                    <div class="serviceFinally__form_content__title">Дневной макияж</div>
                                    <div class="serviceFinally__form_content__price">750 ₽</div>
                                </div>
                                <div class="serviceFinally__form_content__block fic">
                                    <div class="serviceFinally__form_content__items fic">
                                        <div class="accordion__block_master">Елена Грибнова</div>
                                    </div>
                                    <div class="serviceFinally__form_content__item fic">
                                        <div class="serviceFinally__form_content__time">16:30</div>
                                        <div class="serviceFinally__form_content__date">18 ноября</div>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <div class="serviceFinally__form_itesm">
                            <div class="contacts__form_block fic">
                                <input type="text" name="client_name" class="contacts__form_iunput" placeholder="Введите имя"
                                       required="">
                                <div class="contacts__form_inputBlock">
                                    <input type="text" name="phone_number" class="contacts__form_iunput"
                                           placeholder="+7(999)999--99-99" required="">
                                </div>
                            </div>

                            <textarea name="question" class="contacts__form_textarea"
                                      placeholder="Вопрос(необязательно)"></textarea>
                            <div class="contacts__form_checkboxBlock fic">
                                <input type="checkbox" class="contacts__form_checkbox" checked="">
                                <span class="contacts__form_checkboxBlock__intro">Я согласен(а) с политикой конфидециоальности</span>
                            </div>
                            <a href={% url 'beauty:index' %}>
                                <button type="submit" class="serviceFinallys__form_btn">Записаться</button>
                            </a>
                            <a href="#">
                                <button class="serviceFinallys__form_back">Назад</button>
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </section>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js" integrity="sha512-XtmMtDEcNz2j7ekrtHvOVR4iwwaD6o/FUJe6+Zq+HgcCsk3kj4uSQQR8weQ2QVj1o0Pk6PwYLohm206ZzNfubg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	
	<script src="{% static 'beauty/js/main.js' %}"></script>
</body>
{% endblock%}